[build]
  publish = "./"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run serve"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; \
      script-src 'self' 'unsafe-inline' https:; \
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
      img-src 'self' data: https:; \
      font-src 'self' https://fonts.gstatic.com; \
      connect-src 'self'; \
      frame-ancestors 'none'; \
      form-action 'self' https://formspree.io;"
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

[[headers]]
  for = "/src/output.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
