name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build CSS
      run: npm run build
      
    - name: Run tests
      run: npm test
      continue-on-error: true
      
    - name: Verify Netlify Configuration
      run: |
        if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
          echo "::error::NETLIFY_AUTH_TOKEN is not set in repository secrets"
          exit 1
        fi
        if [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then
          echo "::error::NETLIFY_SITE_ID is not set in repository secrets"
          exit 1
        fi
        echo "Netlify configuration verified successfully"
      shell: bash

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 5
      continue-on-error: false
